spring:
  config:
    activate:
      on-profile: local

  application:
    name: Arquetipo de Spring Boot
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://docker-db-1:3306/lease_tech
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
